# Generated by Django 5.2.9 on 2025-12-27 10:50

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Locality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=150, verbose_name='Название города')),
                ('region', models.CharField(max_length=100, verbose_name='Субъект РФ')),
                ('population', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Население')),
                ('oktmo_code', models.CharField(max_length=11, unique=True, verbose_name='Код ОКТМО')),
                ('is_active', models.BooleanField(default=True, help_text="Поле для отладки, исключение 'некорректных городов'", verbose_name='Участвует в рейтинге')),
            ],
            options={
                'verbose_name': 'Город',
                'verbose_name_plural': 'Города',
                'ordering': ['-population'],
            },
        ),
        migrations.CreateModel(
            name='InfrastructureData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schools', models.PositiveSmallIntegerField(default=0, verbose_name='Школы')),
                ('gas_stations', models.PositiveSmallIntegerField(default=0, verbose_name='АЗС')),
                ('bus_stops', models.PositiveSmallIntegerField(default=0, verbose_name='Остановки ОТ')),
                ('locality', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='infrastructure', to='core.locality', verbose_name='Город')),
            ],
            options={
                'verbose_name': 'Инфраструктура',
                'verbose_name_plural': 'Инфраструктура',
            },
        ),
        migrations.CreateModel(
            name='EconomicData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField(verbose_name='Год данных')),
                ('ndfl_total', models.BigIntegerField(verbose_name='НДФЛ всего (руб.)')),
                ('unemployment_rate', models.FloatField(blank=True, null=True, verbose_name='Безработица (%)')),
                ('locality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='economics', to='core.locality', verbose_name='Город')),
            ],
            options={
                'verbose_name': 'Экономические данные',
                'verbose_name_plural': 'Экономические данные',
                'ordering': ['-year'],
                'unique_together': {('locality', 'year')},
            },
        ),
    ]
